version: '3.7'  # 파일 규격 버전

services:       
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - C:\workspace\Docker\volume\prometheus\config:/etc/prometheus
      - C:\workspace\Docker\volume\prometheus\volume:/prometheus
    ports:
      - 9090:9090                                              # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    command: 
      - '--web.enable-lifecycle'                               # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prometheus
